export const ERROR = 'ERROR'

export const ADD_PROJECT = 'ADD_PROJECT'
export const INSERT_PROJECT = 'INSERT_PROJECT'
export const UPDATE_PROJECT = 'UPDATE_PROJECT'

export const ADD_CHECKLIST = 'ADD_CHECKLIST'
export const INSERT_CHECKLIST = 'INSERT_CHECKLIST'
export const UPDATE_CHECKLIST = 'UPDATE_CHECKLIST'

export const SET_SYNC_STATE = 'SET_SYNC_STATE'
