export const ERROR = 'ERROR'
export const RECEIVED_ENTITIES = 'RECEIVED_ENTITIES'

export const SIGNIN = 'SIGNIN'

export const ADD_PROJECT = 'ADD_PROJECT'
export const INSERT_PROJECT = 'INSERT_PROJECT'
export const UPDATE_PROJECT = 'UPDATE_PROJECT'
export const FIND_ALL_PROJECT = 'FIND_ALL_PROJECT'
export const FIND_PROJECT = 'FIND_PROJECT'

export const ADD_CHECKLIST = 'ADD_CHECKLIST'
export const INSERT_CHECKLIST = 'INSERT_CHECKLIST'
export const UPDATE_CHECKLIST = 'UPDATE_CHECKLIST'

export const SET_SYNC_STATE = 'SET_SYNC_STATE'
