# PostgreSQL. Versions 9.1 and up are supported.
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV['DATABASE_POOL'] || ENV['RAILS_MAX_THREADS'] || ENV['PUMA_MAX_THREADS'] || 5 %>

development:
  <<: *default
  database: checklist_web_api_development

test:
  <<: *default
  database: checklist_web_api_test

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
